consulta/urls.py
from django.urls import path
from consulta.views import ConsultaResp

urlpatterns = [
    path('consulta', ConsultaResp.as_view(), name='consultaresp'),
]

librosonline/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vistaprevia/', include('vistaprevia.urls')),
    path('consulta/', include('consulta.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

vistaprevia/urls.py
from django.urls import path
from vistaprevia import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contacto', views.contacto, name='contacto'),
    path('cargar/', views.cargar_imagen, name='cargar'),
    path('<int:producto_id>/ver/', views.ver_imagen, name='ver'),
    path('verimagenes', views.ver_imagenes, name='verimagenes'),
]

consulta/models.py
from django.db import models
from django.core.mail import send_mail
from django.utils.html import format_html
from datetime import datetime

# Create your models here.

class Consulta(models.Model):
    CONTESTADA = 'Contestada'
    NOCONTESTADA = 'No Contestada'
    ENPROCESO = 'En_Proceso'
    DEVOLICIOND = (
        (CONTESTADA, 'Contestada'),
        (NOCONTESTADA, 'No Contestada'),
        (ENPROCESO, 'En Proceso'),
        )

    nombre = models.CharField(max_length=50, blank=True, null=True)
    descripcion = models.TextField( blank=True, null=True)
    mail = models.EmailField(max_length=50, blank=True, null=True)
    estado_respuesta = models.CharField(max_length=15, blank=True,
    choices=DEVOLICIOND, default=NOCONTESTADA)
    fecha = models.DateField(default=datetime.now, blank=True, editable=True)

    def __str__(self):
        return self.nombre

    def estado_de_respuesta(self):
        if self.estado_respuesta == 'Contestada':
            return format_html('<span style="color: #00f;">{}</span>', self.estado_respuesta, )
        elif self.estado_respuesta == 'No Contestada':
            return format_html('<span style="color: #f00;">{}</span>', self.estado_respuesta, )
        elif self.estado_respuesta == 'En_Proceso':
            return format_html('<span style="color: #099;">{}</span>', self.estado_respuesta, )

class Respuesta(models.Model):
    consulta = models.ForeignKey(Consulta, on_delete=models.PROTECT)
    respuesta = models.TextField()
    fecha = models.DateField(default=datetime.now, blank=True, editable=False)

    def create_mensaje(self):
        subject = "Respuesta consulta - CIRSUB"
        from_email="info@mutualcirsubgn.org"
        destino=[self.consulta.mail]
        mensaje_html = self.respuesta
        #send_mail(subject, self.respuesta, from_email, destino, html_message=mensaje_html, fail_silently=False)

        print(self.consulta.id)
        consula_cambio_estado = Consulta.objects.get(id=self.consulta.id)
        print(consula_cambio_estado)
        print(consula_cambio_estado.estado_respuesta)
        consula_cambio_estado.estado_respuesta = "Contestada"
        consula_cambio_estado.save()

    def save(self, *args, **kwargs):
        self.create_mensaje()
        force_update = False

        if self.id:
            force_update = True
            super(Respuesta, self).save(force_update=force_update)

vistaprevia/models.py
from django.db import models
from django.utils.html import format_html

# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)

    def __str__(self):
        return '%s' % self.nombre

class Producto(models.Model):
    Borrador = 'Borrador'
    Publicado = 'Publicado'
    Retirado = 'Retirado'
    APROBACION_PRODUCTO = (
    (Borrador, 'Borrador'),
    (Publicado, 'Publicado'),
    (Retirado, 'Retirado'),
    )

    producto = models.CharField(max_length=200)
    estado = models.CharField(max_length=10, choices=APROBACION_PRODUCTO, default='Borrador')
    fecha_publicacion = models.DateTimeField('Fecha de publicación')
    ruta_imagen = models.FileField(upload_to='fotos/%Y/%m/%d', default='defecto/defecto.png', blank=True, null=True)
    categoria = models.ManyToManyField(Categoria)

    def tipo_de_producto(self):
        if self.estado == 'Retirado':
            return format_html('<span style="color: #f00;">{}</span>', self.estado, )
        elif self.estado == 'Borrador':
            return format_html('<span style="color: #f0f;">{}</span>', self.estado, )
        elif self.estado == 'Publicado':
            return format_html('<span style="color: #099;">{}</span>', self.estado, )

    def __str__(self):
        return ('<%s => %s: %s, %s>' % (self.__class__.__name__, self.producto, self.fecha_publicacion, self.ruta_imagen))

vistaprevia/forms.py
from django.forms import ModelForm
from .models import Producto

class CargarForm(ModelForm):
    class Meta:
        model = Producto
        fields = ['producto', 'fecha_publicacion', 'ruta_imagen']
        error_messages = {
            'producto': {
            'required': ("Se debe agregar un nombre de producto"),
            },
            'fecha_publicacion': {
            'required': ("Se debe agregar la fecha de publicación en el formato adecuado"),
            },
        }
    def __init__(self, *args, **kwargs):
        super(CargarForm, self).__init__(*args, **kwargs)

vistaprevia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import RequestContext, loader

from vistaprevia.models import Producto
from vistaprevia.forms import CargarForm

from django.http import Http404
from django.shortcuts import render_to_response
from django.template import RequestContext

# Create your views here.

# def index(request):
#     return HttpResponse("Hola Maxi!")

def index(request):
    contenido = { 'nombre_sitio': 'LibrosOnline' }
    para_minorista = { 'tipo_usuario' : 'minorista' , 'incremento' : '25'}
    para_mayorista = { 'tipo_usuario' : 'mayorista' , 'incremento' : '10'}
    # return render(request, 'vistaprevia/index.html', contenido)
    return render(request,
                'vistaprevia/index.html', {'contenido':contenido,
                'para_minorista':para_minorista,
                'para_mayorista':para_mayorista})

def contacto(request):
    return render(request, 'vistaprevia/contacto.html')

def cargar_imagen(request):
    if request.method == 'POST':
        form = CargarForm(request.POST, request.FILES)
        if form.is_valid():
            producto = form.cleaned_data['producto']
            fecha_publicacion = form.cleaned_data['fecha_publicacion']
            ruta_imagen = form.cleaned_data['ruta_imagen']
            newdoc = Producto(producto = producto, fecha_publicacion = fecha_publicacion,
                    ruta_imagen = ruta_imagen)
            newdoc.save()
            return redirect("index")
    else:
        form = CargarForm()
    return render(request, 'vistaprevia/formulario.html', {'form': form})


def ver_imagen(request, producto_id):
    try:
        producto = Producto.objects.get(pk=producto_id)
    except Producto.DoesNotExist:
        raise Http404
    return render_to_response('vistaprevia/verimagen.html', {
            'producto': producto,
            'error_message': "No has seleccionado un producto.",
            },content_type=RequestContext(request))

def ver_imagenes(request):
    try:
        productos = Producto.objects.all()
    except Producto.DoesNotExist:
        raise Http404
    return render_to_response('vistaprevia/verimagenes.html', {
            'productos': productos,
            'error_message': "No has seleccionado un producto.",
            },content_type=RequestContext(request))

templates/vistaprevia/contacto.html
{% extends "plantilla.html" %}
{% load static %}
{% load  i18n %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>Página de contacto.</h1>
  </div>
</div>
<main class="container-fluid">
    <div id="formulario_contacto" class="row">

            <div class="col-xs-offset-1 col-xs-10 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
                <h2>Contacto</h2>
                <hr/>
                <form id="contact" action="" method="post" class="col-xs-12">
                  {% csrf_token %}
                    <div class="col-xs-12">
                        <label id="label_nombre_completo" for="id_nombre_completo">NOMBRE Y APELLIDO</label>
                        <input type="text" name="nombre">
                    </div>
                    <div class="col-xs-12">
                        <label id="label_email" for="id_email">EMAIL</label>
                        <input type="text" name="mail"/>
                    </div>
                    <div class="col-xs-12">
                        <label  for="id_fecha">Fecha Límite de entrega</label>
                        <input id="id_fecha"  type="text" name="fecha"/>
                    </div>
                    <div class="col-xs-12">
                        <label id="label_mensaje" for="id_mensaje">CONSULTA</label>
                        <textarea name="consulta" ></textarea>
                    </div>
                    <button type="submit" class="col-xs-offset-3 col-xs-6 btn btn-default bt-form">Enviar</button>

                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}


{% block scripts %}
    <script src="{% static 'vistaprevia/js/jquery-ui.js' %}"></script>
    <script> $("#id_fecha" ).datepicker({
             inline: true
             });
    </script>
{% endblock %}

templates/vistaprevia/formulario.html
{% extends "plantilla.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<div class="container">
<div class="jumbotron">
<h1>Página de contacto.</h1>
</div>
</div>
<main class="container-fluid">
<div id="formulario_contacto" class="row">
<div class="col-xs-offset-1 col-xs-10 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
<h2>Contacto</h2>
<hr/>
<form class="col-xs-12" action="{% url 'cargar' %}"
method="post" enctype="multipart/form-data">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit">
</form>
</div>
</div>
</main>
{% endblock %}
{% block scripts %}
<script src="{% static 'vistaprevia/js/jquery-ui.js' %}"></script>
<script>
$( "#id_fecha_publicacion" ).datepicker({
inline: true
});
</script>
{% endblock %}

templates/vistaprevia/index.html
{% extends "plantilla.html" %}
{% load static %}
{% load  i18n %}
{% block content %}
  <div class="container">
    <div class="jumbotron">
      <h1>Bienvenido a : {{contenido.nombre_sitio}}.!</h1>
    </div>
  </div>
  <main class="container">
    <div class="row">
      <section class="col-12" style="background-color:#25b89a; color: #fff; ">
      {% if para_minorista.incremento == '10' %}
        <h2>El incremento para minoristas es del:
          {{para_minorista.incremento}}%.!</h2>
      {% elif para_minorista.incremento == '20' %}
        <h2>El incremento para minoristas es del:
          {{para_minorista.incremento}}%.!</h2>
      {% else %}
        <h2>El incremento para minoristas es del:
          {{para_minorista.incremento}}%.!</h2>
      {% endif%}
      {% block scripts %}
      <script type="text/javascript">$('a').click(function(){alert("Estas por ir a otra página");});</script>
      {% endblock %}
      </section>
    </div>
  </main>
{% endblock %}

templates/vistaprevia/verimagen.html
{% extends "plantilla.html" %}
{% load static %}
{% load i18n %}
{% block content %}
 <div class="container">
	<div class="jumbotron">
		<h2>Ver Cada Imagen</h2>
	</div>
 </div>
 <main class="container">
	<div class="row" >
		<section class="col-12" style=" padding:30px; 30px; 230px; 30px;">
			<h1> El id de la imagen es: {{ producto.id }}</h1>
			{% load staticfiles %}
				<img src="/media/{{producto.ruta_imagen}}" alt="My image" width="20%"/>
				<a href="{% url 'verimagenes' %}">Ver todas las imagenes</a>
		</section>
	</div>
 </main>
{% endblock %}

templates/vistaprevia/verimagenes.html
{% extends "plantilla.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<div class="container">
	<div class="jumbotron">
		<h2>Ver Cada Todas las Imagenes</h2>
	</div>
</div>
<main class="container">
	<div class="row" >
		<section class="col-12" style=" padding:30px; 30px; 230px; 30px;">
			{% for productos in productos %}
				<a href="{% url 'ver' productos.id %}">
					<img src="/media/{{productos.ruta_imagen}}" alt="My image" width="20%"/>
				</a>
			{% endfor %}
		</section>
	</div>
 </main>
{% endblock %}